name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: check current path
        run: cd
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-windows.zip
          path: build/windows/x64/runner/Release

