name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: check current path
        run: cd
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
            node-version: 20
      - name: install evb
        run: npm install enigmavirtualbox -g
      - name: move build result
        run: move "build\windows\x64\runner\Release\renamer.exe" "renamer.exe"
      - name: create dat
        run: tar.exe -a -c -f renamer.dat "build\windows\x64\runner\Release\*"
      - name: create evb config file
        run: enigmavirtualbox gen renamer.evb renamer-bundled.exe renamer.exe renamer.dat
      - name: build single exe file
        run: enigmavirtualbox cli .\renamer.evb
      - name: Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: renamer-${{github.ref_name}}-${{ github.sha }}-windows
          path: build/windows/x64/runner/Release

#  build-and-release-macos:
#    runs-on: macos-14
#
#    steps:
#      - uses: actions/checkout@v4
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: 'stable'
#          architecture: x64
#          flutter-version: '3.19.1'
#      - name: Install project dependencies
#        run: flutter pub get
#      - name: Enable macOS build
#        run: flutter config --enable-macos-desktop
#      - name: Build artifacts
#        run: flutter build macos --release
#      - name: install npm
#        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
#      - name: install appdmg
#        run: npm install -g appdmg
#      - name: build dmg
#        run: appdmg ./dmg/config.json ./build/macos/Build/Products/Release/renamer.dmg
#      - name: macOS Release
#        uses: actions/upload-artifact@v4
#        with:
#          name: renamer-${{github.ref_name}}-${{ github.sha }}-macos
#          path: build/macos/Build/Products/Release/renamer.dmg

