name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: check current path
        run: cd
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: install evb
        run: curl.exe -o .\enigmavbconsole.exe "https://drive.usercontent.google.com/download?id=1j6ETwhO0NTn_QF8yrSBbczGpgh5AoMt4&export=download&authuser=0&confirm=t&uuid=ca7c2bc1-0ab1-4456-9cd6-fa79fa9aeedc&at=APZUnTU856nDSXEw3OhFsSMN3Lha%3A1709011511832"
      - name: build single exe file
        run: .\enigmavbconsole.exe .\evb\renamer_evb.evb
      - name: Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-windows.zip
          path: build/windows/x64/runner/Release

