name: Flutter CI

on: push

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-0 libgtk-3-dev libblkid1 liblzma5
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable linux build
        run: flutter config --enable-linux-desktop
      - name: Build artifacts
        run: flutter build linux --release
      - name: Build Appimage
        run: bash ./github_appimage_build.sh
      - name: Linux Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-linux.zip
          path: build/linux/x64/release/bundle

  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: check current path
        run: ECHO %cd%
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-windows.zip
          path: build/windows/x64/runner/Release

  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: macOS Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-macos.zip
          path: build/macos/Build/Products/Release