name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - name: check current path
        run: cd
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: install npm
        run: msiexec.exe /a https://nodejs.org/dist/v20.11.1/node-v20.11.1-x64.msi /quiet
      - name: install evb
        run: npm install enigmavirtualbox
      - name: build single exe file
        run: enigmavirtualbox cli .\evb\renamer_evb.evb
      - name: Windows Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-windows.zip
          path: build/windows/x64/runner/Release

  build-and-release-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          flutter-version: '3.19.1'
      - name: Install project dependencies
        run: flutter pub get
      - name: Enable macOS build
        run: flutter config --enable-macos-desktop
      - name: Build artifacts
        run: flutter build macos --release
      - name: install npm
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: install appdmg
        run: npm install -g appdmg
      - name: build dmg
        run: appdmg ./dmg/config.json ./build/macos/Build/Products/Release/renamer.dmg
      - name: macOS Release
        uses: actions/upload-artifact@v4
        with:
          name: Renamer-${{github.ref_name}}-macos.zip
          path: build/macos/Build/Products/Release

